branch-defaults:
  master:
    environment: production
    group_suffix: null
global:
  application_name: primedb
  branch: null
  default_ec2_keyname: null
  default_platform: python-3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
